declare namespace NodeJS {
  interface ProcessEnv {
    OPENAI_ENDPOINT: string
    OPENAI_APIKEY: string

    NEXT_PUBLIC_FIREBASE_API_KEY: string
    NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN: string
    NEXT_PUBLIC_FIREBASE_PROJECT_ID: string
    NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET: string
    NEXT_PUBLIC_FIREBASE_MESSAGE_SENDER_ID: number
    NEXT_PUBLIC_FIREBASE_APP_ID: string
  }
}
